import 'fake-indexeddb/auto';
(globalThis as any).window = globalThis; (globalThis as any).document = { visibilityState: 'visible', addEventListener(){}, removeEventListener(){} };
const { db } = await import('../src/lib/db.ts');
const { seedIfNeeded } = await import('../src/data/seed.ts');
const { buildSnapshot } = await import('../src/lib/widget.ts');
console.log('seeded', await seedIfNeeded());
console.log('events', await db.events.count(), 'notes', await db.notes.count(), 'lectures', await db.lectures.count(), 'alarms', await db.alarms.count());
const l = await db.lectures.toArray();
const txt = await l[0].blob.text();
console.log('pdf ok', txt.startsWith('%PDF-1.4'), txt.length, 'endswith EOF', txt.trim().endsWith('%%EOF'));
const snap = await buildSnapshot();
console.log('snapshot', snap.events.length, 'events today;', 'deadlines', snap.deadlines.map(d=>d.title));
console.log('second seed', await seedIfNeeded());
